package com.mycompany.numericmaster;

import javax.swing.JTextField;

public class MethodSelection extends javax.swing.JPanel {
    
    // Declare pointer to other panels
    Muller pointerToMullerPanel;
    Cramer pointerToCramerPanel;
    Midpoint pointerToMidpointPanel;
    
    public MethodSelection() {
        initComponents();
        
        // Initialize pointer to other panels
        pointerToMullerPanel = null;
        pointerToCramerPanel = null;
        pointerToMidpointPanel = null;
        
        
        
    }
    
    // set pointer to muller panel
    public void setPointerToMullerPanel(Muller panel) {
        pointerToMullerPanel = panel;
    }
    
    // set pointer to cramer panel
    public void setPointerToCramerPanel(Cramer panel) {
        pointerToCramerPanel = panel;
    }
    
    // set pointer to midpoint panel
    public void setPointerToMidpointPanel(Midpoint panel) {
        pointerToMidpointPanel = panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mullerLblBtn = new javax.swing.JLabel();
        cramerLblBtn = new javax.swing.JLabel();
        midpointLblBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mullerLblBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ICON FOR MULLERS S.png"))); // NOI18N
        mullerLblBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mullerLblBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mullerLblBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mullerLblBtnMousePressed(evt);
            }
        });
        add(mullerLblBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        cramerLblBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ICON FOR CRAMERS S.png"))); // NOI18N
        cramerLblBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cramerLblBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cramerLblBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cramerLblBtnMousePressed(evt);
            }
        });
        add(cramerLblBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        midpointLblBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ICON FOR MIDPOINT s.png"))); // NOI18N
        midpointLblBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                midpointLblBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                midpointLblBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                midpointLblBtnMousePressed(evt);
            }
        });
        add(midpointLblBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/WELCOME PAGE.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void mullerLblBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mullerLblBtnMouseEntered
        // TODO add your handling code here:
        mullerLblBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ICON FOR mullers enter .png"))); // NOI18N
        
    }//GEN-LAST:event_mullerLblBtnMouseEntered

    private void mullerLblBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mullerLblBtnMousePressed
        // hides this panel and show the muller panel
        setVisible(false);
        pointerToMullerPanel.setVisible(true);
        
    }//GEN-LAST:event_mullerLblBtnMousePressed

    private void cramerLblBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cramerLblBtnMousePressed
        // hides this panel and show the cramer panel
        setVisible(false);
        pointerToCramerPanel.setVisible(true);
    }//GEN-LAST:event_cramerLblBtnMousePressed

    private void midpointLblBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_midpointLblBtnMousePressed
        // hides this panel and show the midpoint panel
        setVisible(false);
        pointerToMidpointPanel.setVisible(true);
    }//GEN-LAST:event_midpointLblBtnMousePressed

    private void mullerLblBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mullerLblBtnMouseExited
        // TODO add your handling code here:
        mullerLblBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ICON FOR MULLERS S.png"))); // NOI18N
    }//GEN-LAST:event_mullerLblBtnMouseExited

    private void cramerLblBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cramerLblBtnMouseExited
        // TODO add your handling code here:
       cramerLblBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ICON FOR CRAMERS S.png"))); // NOI18N
    }//GEN-LAST:event_cramerLblBtnMouseExited

    private void cramerLblBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cramerLblBtnMouseEntered
        // TODO add your handling code here:
       cramerLblBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ICON FOR CRAMERS ENTER.png"))); // NOI18N
    }//GEN-LAST:event_cramerLblBtnMouseEntered

    private void midpointLblBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_midpointLblBtnMouseExited
        // TODO add your handling code here:
       midpointLblBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ICON FOR MIDPOINT s.png"))); // NOI18N
    }//GEN-LAST:event_midpointLblBtnMouseExited

    private void midpointLblBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_midpointLblBtnMouseEntered
        // TODO add your handling code here:
       midpointLblBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ICON FOR MIDPOINT ENTER.png"))); // NOI18N
    }//GEN-LAST:event_midpointLblBtnMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cramerLblBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel midpointLblBtn;
    private javax.swing.JLabel mullerLblBtn;
    // End of variables declaration//GEN-END:variables
}
